### PR TITLE
Fix drugs record table

### LINKED ISSUE #276: add PMIDs/Sources field to Drug Record page
related to #275, drug record page is missing PMID/Source information within interaction results table.

### PR DESCRIPTION
**Pull request by mcannon068nw**
closes #276 

Added sources/pmid retrieval to gql query and added back these fields to the individual record page.

### CODE REVIEW

File: client/src/hooks/queries/useGetInteractions.ts [hunk 1]
```diff
@@ -63,6 +63,13 @@ const getInteractionsByDrugsQuery = gql`
             type
             directionality
           }
+          publications {
+            pmid
+          }
+          sources {
+            id
```
Comment (jsstevenson) [inline client/src/hooks/queries/useGetInteractions.ts:70]: We shouldn't need to pull ID for anything on the frontend -- this can be removed

**Review by jsstevenson — CHANGES_REQUESTED** [review]

**Review by jsstevenson — APPROVED** [review]
