### PR TITLE
fix: data cleaning

### LINKED ISSUE #210: Data cleaning

### PR DESCRIPTION
**Pull request by jsstevenson**
Close #210, #104, #105, #65, #44, #27

A few outstanding questions for the neighborhood pharmacology expert but should be smooth otherwise. I also flagged one design question for Adam.

### CODE REVIEW

File: server/db/seeds.rb [hunk 1]
```diff
@@ -33,23 +33,17 @@
...
   },
   {
-    type: 'partial agonist',
-    directionality: 0,
-    definition: 'In a partial agonist interaction, a drug will elicit a reduced amplitude functional response at its target receptor, as compared to the response elicited by a full agonist.',
-    reference: '<a href="https://en.wikipedia.org/wiki/Receptor_antagonist#Partial_agonists">Wikipedia - Receptor Antagonist</a>'
+    type: 'antibody',
+    directionality: 1,
+    definition: 'TODO',
+    reference: 'TODO'
```
Comment (jsstevenson) [inline server/db/seeds.rb:46]: @mcannon068nw input pls

File: server/db/seeds.rb [hunk 2]
```diff
@@ -200,6 +188,24 @@
...
+    type: 'immunotherapy',
+    directionality: nil,
+    definition: 'Immunotherapy is used to upregulate or downregulate the immune system to achieve a therapeutic effect in immunological mediated disorders, including immunodeficiencies, hypersensitivity reactions, autoimmune diseases, tissue and organ transplantations, malignancies, inflammatory disorders, infectious diseases, and any other disease, where immunotherapy can improve the quality and life expectancy.',
+    reference: 'https://www.ncbi.nlm.nih.gov/books/NBK519046/'
+  },
+  {
+    type: 'cytotoxic',
+    directionality: nil,  # TODO
+    definition: 'TODO',  # TODO
+    reference: 'TODO'  # TODO
```
Comment (jsstevenson) [inline server/db/seeds.rb:208]: @mcannon068nw input pls

File: server/db/seeds.rb [hunk 3]
```diff
@@ -200,6 +188,24 @@
     directionality: nil,
     definition: 'Substrates are drugs which are metabolized by the protein they are interacting with.',
     reference: '<a href="https://www.fda.gov/drugs/drug-interactions-labeling/drug-development-and-drug-interactions-table-substrates-inhibitors-and-inducers">FDA - Table of Substrates, Inhibitors and Inducers</a>'
+  },
+  {
+    type: 'vaccine',
+    directionality: 0,
+    definition: 'In vaccine interactions, the drugs stimulate or restore an immune response to their target.',
+    reference: '<a href="https://www.cancer.gov/about-cancer/treatment/types/immunotherapy#q3">NCI - Cancer Vaccines</a>'
```
Comment (jsstevenson) [inline server/db/seeds.rb:196]: Would like to revisit this style of data presentation when we cover the Sources page (in I think #170) because it's pretty janky to dump raw html into the database

File: server/lib/genome/names.rb [hunk 4]
```diff
@@ -0,0 +1,120 @@
+module Genome
```
Comment (jsstevenson) [inline server/lib/genome/names.rb:1]: @acoffman this seemed like a straightforward way to get something like a shared set of enums (rather than ruby symbols) to standardize values across importers/groupers/normalizers. Is this sufficiently idiomatic? Any suggestions?

File: server/db/seeds.rb (hunk 1 above)
Comment (mcannon068nw) [reply server/db/seeds.rb:46]: type: 'antibody',
    directionality: 1,
    definition: 'An antibody interaction occurs when an antibody drug specifically binds the target molecule. Most interactions of this class fall under various natural antibody functions: neutralization, antibody-dependent cell-mediated cytotoxicity (ADCC), complement-dependent cytotoxicity (CDC), or drug delivery carriers.', 
    reference: '<a href="https://www.ncbi.nlm.nih.gov/pubmed/26441475/">pubmed:26441475</a>'

File: server/lib/genome/names.rb (hunk 4 above)
Comment (acoffman) [reply server/lib/genome/names.rb:1]: You can add 
`# frozen_string_literal: true` 

As the first line in the file rather than `.freeze` everywhere for this sort of thing if you prefer. You _could_ potentially make these dictionaries/hashes, but based on the usage elsewhere in this PR I think I agree that consts are actually better here!
